LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE:= Superuser
LOCAL_SRC_FILES:= Superuser.apk
LOCAL_CERTIFICATE:= platform
LOCAL_MODULE_CLASS:= APPS
#LOCAL_MODULE_PATH:= system/app
LOCAL_MODULE_SUFFIX:= $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
